Update trigger-pipelines.yml

diff --git a/.github/workflows/trigger-pipelines.yml b/.github/workflows/trigger-pipelines.yml
--- a/.github/workflows/trigger-pipelines.yml
+++ b/.github/workflows/trigger-pipelines.yml
@@ -22,5 +22,15 @@ jobs:
       matrix:
         job_name: ${{ fromJson(needs.generate-jobs.outputs.jobs) }}
     steps:
-      - name: Run ${{ matrix.job_name }}
-        run: echo "Running job: ${{ matrix.job_name }}"
+      - name: Trigger deploy pipeline for  ${{ matrix.job_name }} appliation
+        run: |
+          app_name="${{ matrix.job_name  }}"
+          if [[ ! " ${options[@]} " =~ " ${app_name} " ]]; then
+            echo "Invalid application name: $app_name"
+            exit 1
+          fi
+          curl -X POST \
+            -H "Accept: application/vnd.github.v3+json" \
+            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+            https://api.github.com/repos/YOUR_USERNAME/repo-B/actions/workflows/deploy.yml/dispatches \
+            -d "{\"ref\":\"main\", \"inputs\": {\"app_name\": \"$app_name\"}}"
